### ISSUE TITLE
Oubli de la balise html ligne 1

### ISSUE THREAD

**Issue by itsnatedel** [belkacem98/EPFC#1]
Tu as fermé la balise html ligne 42 sans l'avoir ouvert dans ton code

**Comment by belkacem98** [comment]
Trop fort

**Comment by belkacem98** [comment]
MAIS tu as écris ça et je ne sais pas de quel code tu parle ici

**Comment by itsnatedel** [comment]
petit à petit on commence à comprendre le site mdrr des vrais noobs srx
